CREATE DATABASE hospital_team_37;
\connect hospital_team_37

DROP SCHEMA IF EXISTS public CASCADE; 
CREATE SCHEMA public;

CREATE TABLE IF NOT EXISTS "DEPARTMENT" (
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Building_number" INTEGER NOT NULL,
    "Room_number" INTEGER NOT NULL,
    CONSTRAINT uq_department_location UNIQUE ("Building_number", "Room_number")
);

CREATE TABLE IF NOT EXISTS "DOCTOR" (
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Full_name" TEXT NOT NULL,
    "Specialization" TEXT NOT NULL,
    "Phone" TEXT NOT NULL UNIQUE CHECK ("Phone" ~ '^[+0-9 ()-]{7,20}$'),
    "Email" TEXT NOT NULL UNIQUE CHECK ("Email" ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
    "Hire_date" DATE NOT NULL,
    "Licence_number" INTEGER UNIQUE NOT NULL,
    "Department_ID" INTEGER NOT NULL REFERENCES "DEPARTMENT"("ID")
);

CREATE TABLE IF NOT EXISTS "PATIENT" (
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Full_name" TEXT NOT NULL,
    "National_ID" INTEGER UNIQUE NOT NULL,
    "Date_of_birth" DATE NOT NULL,
    "Gender" TEXT NOT NULL CHECK ("Gender" IN ('male', 'female')),
    "Phone" TEXT NOT NULL UNIQUE CHECK ("Phone" ~ '^[+0-9 ()-]{7,20}$'),
    "Email" TEXT NOT NULL UNIQUE CHECK ("Email" ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
    "Address" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "APPOINTMENT" (
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Date" DATE NOT NULL,
    "Time" TIME NOT NULL,
    "Status" TEXT NOT NULL CHECK ("Status" IN ('scheduled', 'completed', 'cancelled')),
    "Doctor_ID" INTEGER NOT NULL REFERENCES "DOCTOR"("ID"),
    "Patient_ID" INTEGER NOT NULL REFERENCES "PATIENT"("ID")
);

CREATE TABLE IF NOT EXISTS "DIAGNOSIS" (
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" TEXT NOT NULL,
    "Description" TEXT NOT NULL,
    "Appointment_ID" INTEGER NOT NULL UNIQUE
        REFERENCES "APPOINTMENT"("ID") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "PROCEDURE" (
    "ID" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Price" NUMERIC(10, 2) NOT NULL CHECK ("Price" > 0)
);

CREATE TABLE IF NOT EXISTS "APPOINTMENT_PROCEDURE" (
    "Appointment_ID" INTEGER NOT NULL REFERENCES "APPOINTMENT"("ID") ON DELETE CASCADE,
    "Procedure_ID" INTEGER NOT NULL REFERENCES "PROCEDURE"("ID"),
    PRIMARY KEY ("Appointment_ID", "Procedure_ID")
);

INSERT INTO "DEPARTMENT" ("Name", "Building_number", "Room_number") VALUES
  ('Cardiology', 1, 101),
  ('Neurology', 1, 102),
  ('Pediatrics', 2, 201),
  ('Orthopedics', 2, 202),
  ('Dermatology', 3, 301),
  ('Oncology', 3, 302),
  ('Emergency', 4, 401),
  ('Radiology', 4, 402),
  ('Ophthalmology', 5, 501),
  ('ENT', 5, 502);

INSERT INTO "DOCTOR"
("Full_name", "Specialization", "Phone", "Email", "Hire_date", "Licence_number", "Department_ID")
VALUES
  ('Ivan Petrov',        'Cardiologist',    '+31612345678',   'ivan.petrov@hospital.test',        '2018-04-12', 120001, 1), 
  ('Anna Smirnova',      'Neurologist',     '+4915123456789', 'anna.smirnova@hospital.test',      '2019-09-03', 120002, 2),  
  ('Oleg Kuznetsov',     'Pediatrician',    '+33612345678',   'oleg.kuznetsov@hospital.test',     '2020-02-18', 120003, 3),  
  ('Maria Volkova',      'Orthopedist',     '+447911123456',  'maria.volkova@hospital.test',      '2017-11-27', 120004, 4),  
  ('Sergey Ivanov',      'Dermatologist',   '+12125550123',   'sergey.ivanov@hospital.test',      '2021-06-10', 120005, 5),  
  ('Elena Fedorova',     'Oncologist',      '+34600111222',   'elena.fedorova@hospital.test',     '2016-01-15', 120006, 6),  
  ('Dmitry Sokolov',     'ER Physician',    '+393331234567',  'dmitry.sokolov@hospital.test',     '2022-03-05', 120007, 7),  
  ('Natalia Orlova',     'Radiologist',     '+48500123456',   'natalia.orlova@hospital.test',     '2015-08-22', 120008, 8),  
  ('Pavel Morozov',      'Ophthalmologist', '+46701234567',   'pavel.morozov@hospital.test',      '2019-12-02', 120009, 9),  
  ('Yulia Belova',       'ENT Specialist',  '+905321234567',  'yulia.belova@hospital.test',       '2020-07-19', 120010, 10); 

INSERT INTO "PATIENT"
("Full_name", "National_ID", "Date_of_birth", "Gender", "Phone", "Email", "Address")
VALUES
  ('Ksenia Pankova',     920000001, '1999-05-14', 'female', '+31611111111',  'ksenia.pankova@patients.test', 'Dronten, NL'),
  ('Alex Johnson',       920000002, '1988-10-02', 'male',   '+14155550123',  'alex.johnson@patients.test',   'San Francisco, US'),
  ('Maria Garcia',       920000003, '1976-03-21', 'female', '+34600999888',  'maria.garcia@patients.test',   'Madrid, ES'),
  ('Liam Smith',         920000004, '2001-12-11', 'male',   '+447700900123', 'liam.smith@patients.test',     'London, UK'),
  ('Sofia Rossi',        920000005, '1993-07-08', 'female', '+393201234567', 'sofia.rossi@patients.test',    'Milan, IT'),
  ('Noah Brown',         920000006, '1982-01-30', 'male',   '+491711234567', 'noah.brown@patients.test',     'Berlin, DE'),
  ('Emma Wilson',        920000007, '1990-09-17', 'female', '+33698765432',  'emma.wilson@patients.test',    'Lyon, FR'),
  ('Ethan Davis',        920000008, '1971-06-05', 'male',   '+48512123456',  'ethan.davis@patients.test',    'Warsaw, PL'),
  ('Olivia Miller',      920000009, '2004-02-26', 'female', '+46739876543',  'olivia.miller@patients.test',  'Stockholm, SE'),
  ('Mason Taylor',       920000010, '1965-11-09', 'male',   '+905551112233', 'mason.taylor@patients.test',   'Istanbul, TR');

INSERT INTO "APPOINTMENT"
("Date", "Time", "Status", "Doctor_ID", "Patient_ID")
VALUES
  ('2026-02-01', '09:00', 'scheduled',  1,  1),
  ('2026-02-02', '10:30', 'completed',  2,  2),
  ('2026-02-03', '11:15', 'scheduled',  3,  3),
  ('2026-02-04', '14:00', 'cancelled',  4,  4),
  ('2026-02-05', '15:45', 'completed',  5,  5),
  ('2026-02-06', '08:20', 'scheduled',  6,  6),
  ('2026-02-07', '13:10', 'completed',  7,  7),
  ('2026-02-08', '16:30', 'scheduled',  8,  8),
  ('2026-02-09', '12:05', 'completed',  9,  9),
  ('2026-02-10', '17:50', 'scheduled', 10, 10);

INSERT INTO "DIAGNOSIS"
("Title", "Description", "Appointment_ID")
VALUES
  ('Hypertension',            'Elevated blood pressure observed; lifestyle changes advised.', 1),
  ('Migraine',                'Recurrent headaches with aura; prescribed triptan therapy.',    2),
  ('Acute bronchitis',        'Cough and mild fever; supportive care recommended.',            3),
  ('Ankle sprain',            'Ligament strain; rest, ice, compression, elevation.',           4),
  ('Atopic dermatitis',       'Skin inflammation; topical treatment prescribed.',              5),
  ('Screening follow-up',     'Further imaging recommended; follow-up scheduled.',             6),
  ('Gastroenteritis',         'Hydration plan and diet guidance provided.',                    7),
  ('Suspected fracture',      'X-ray required; temporary immobilization applied.',             8),
  ('Conjunctivitis',          'Eye irritation; drops prescribed.',                              9),
  ('Otitis media',            'Ear infection; treatment recommended.',                          10);

INSERT INTO "PROCEDURE" ("Name", "Price") VALUES
  ('ECG', 50.53),
  ('MRI Scan', 600.00),
  ('X-Ray', 120.12),
  ('Blood Test Panel', 80.00),
  ('Ultrasound', 200.00),
  ('Skin Biopsy', 250.00),
  ('CT Scan', 450.00),
  ('Vaccination', 40.00),
  ('Eye Examination', 67.67),
  ('ENT Endoscopy', 180.00);

INSERT INTO "APPOINTMENT_PROCEDURE" ("Appointment_ID", "Procedure_ID") VALUES
  (1, 1),  (1, 4),
  (2, 2),  (2, 7),
  (3, 4),  (3, 8),
  (4, 3),  (4, 5),
  (5, 6),  (5, 4),
  (6, 5),  (6, 4),
  (7, 4),  (7, 8),
  (8, 3),  (8, 7),
  (9, 9),  (9, 4),
  (10,10), (10,3);